---
title: "Data Visualization II"
author: Yuen
date: 10/26/2021
output: 
  github_document
---

```{r setup}
library(tidyverse)
#for density and ridge plots
library(patchwork)
```

```{r}
#load the weather dataset
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

weather_df

```


## Remeber this plot..?

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.5)
```

## Labels

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maximum daily temperature (C)",
    caption = "Data from rnoaa package: temperatures in 2017"
  )
```


## Scales

Start with the same plot, x and y scales

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maximum daily temperature (C)",
    caption = "Data from rnoaa package: temperatures in 2017"
  ) +
  scale_x_continuous(
    breaks = c(-15,0,15),
    labels = c("-15 C", "0", "15")
  ) + 
  scale_y_continuous(
    #transformation
    trans = "sqrt",
    position = "right"
  )
```


Look at color scales

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maximum daily temperature (C)",
    caption = "Data from rnoaa package: temperatures in 2017"
  ) + 
  #define your own color
  scale_color_hue(
    #change the title of the color scale
    name = "Location",
    h = c(100,300))
```

use color palettes - viridis

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maximum daily temperature (C)",
    caption = "Data from rnoaa package: temperatures in 2017"
  ) + 
  viridis::scale_color_viridis(
    #change the title of the color scale
    name = "Location",
    discrete = T)
```


## Themes

Shift the Legend

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maximum daily temperature (C)",
    caption = "Data from rnoaa package: temperatures in 2017"
  ) + 
  viridis::scale_color_viridis(
    #change the title of the color scale
    name = "Location",
    discrete = T) + 
  theme(legend.position = "bottom")
```


Change the overall theme

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maximum daily temperature (C)",
    caption = "Data from rnoaa package: temperatures in 2017"
  ) + 
  viridis::scale_color_viridis(
    #change the title of the color scale
    name = "Location",
    discrete = T) +
  # in the ggthemes() package
  #theme_bw()
  theme_minimal() +
  theme(legend.position = "bottom")

```
































